PROJECT_NAME="YOUR_PROJECT_NAME"
PROJECT_VERSION="1.0.0"
RELEASE="enabled"
RETENTION_DAYS="1"
JAVA_VERSION="8"
PYTHON_VERSION="3.10"
NODE_VERSION="18"
NODE_DIST_DIR="dist/"
PYTHON_DIST_DIR="./"
JAVA_DIST_DIR="target/"
JAVA_DISTRIBUTION="temurin"
TESTING="disabled"
SONAR="disabled"
DOCKER_TAG="latest"
DOCKER_REPOSITORY="YOUR_DOCKER_REPOSITORY"