PROJECT_NAME="gawg"
PROJECT_VERSION="0.0.1"
RELEASE="enabled"
RETENTION_DAYS="1"
JAVA_VERSION="8"
PYTHON_VERSION="3.10"
NODE_VERSION="18"
NODE_DIST_DIR="dist/"
PYTHON_DIST_DIR="./"
JAVA_DIST_DIR="target/"
JAVA_DISTRIBUTION="temurin"
TESTING="enabled"
SONAR="enabled"
SONAR_PROJECTBASEDIR="src"
SONAR_ORGANIZATION="alvarogarciapiz"
SONAR_PROJECTKEY="alvarogarciapiz_gawg"