PROJECT_NAME="YOUR_PROJECT_NAME"
PROJECT_VERSION="1.0.0"
RELEASE="enabled"
RETENTION_DAYS="1"
TESTING="disabled"
SONAR="disabled"
DOCKER_TAG="latest"
DOCKER_REPOSITORY="YOUR_DOCKER_REPOSITORY"
[[DYNAMIC_CONFIG]]